{"name": "test_get_orders_with_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_get_orders.TestGetOrders object at 0x100c5d580>\nauth_header = {'Authorization': 'Bearer Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDdjZWRjOWVkMjgwMDAxYjUyNjdlNCIsImlhdCI6MTczMjc2ODcyMCwiZXhwIjoxNzMyNzY5OTIwfQ.9ZSq7T4AmWd1abAG2tC3fEUHRKOSMngaj5shoM9uRzQ'}\n\n    @allure.feature(\"Получение заказов\")\n    @allure.story(\"Получение заказов авторизованного пользователя\")\n    def test_get_orders_with_auth(self, auth_header):\n        response = requests.get(f\"{BASE_URL}/orders\", headers=auth_header)\n>       assert response.status_code == 200\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntest_get_orders.py:12: AssertionError"}, "start": 1732768720256, "stop": 1732768720544, "uuid": "ac0b90b0-6235-457c-b343-442c4449bfec", "historyId": "2fab9c5df7879b7e1f6bf1dc568f2457", "testCaseId": "2fab9c5df7879b7e1f6bf1dc568f2457", "fullName": "tests.test_get_orders.TestGetOrders#test_get_orders_with_auth", "labels": [{"name": "story", "value": "Получение заказов авторизованного пользователя"}, {"name": "feature", "value": "Получение заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetOrders"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "26592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}