{"name": "test_get_orders_with_auth", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_get_orders.TestGetOrders object at 0x10285e9f0>, auth_header = {'Authorization': 'Bearer <accessToken>'}\n\n    @allure.feature(\"Получение заказов\")\n    @allure.story(\"Получение заказов авторизованного пользователя\")\n    def test_get_orders_with_auth(self, auth_header):\n        response = requests.get(f\"{BASE_URL}/orders\", headers=auth_header)\n>       assert response.status_code == 200  # Ожидаем успешное получение заказов\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntests/test_get_orders.py:18: AssertionError"}, "start": 1732755522215, "stop": 1732755522492, "uuid": "df190fca-db4a-4acd-b78a-da9fbefc771f", "historyId": "2fab9c5df7879b7e1f6bf1dc568f2457", "testCaseId": "2fab9c5df7879b7e1f6bf1dc568f2457", "fullName": "tests.test_get_orders.TestGetOrders#test_get_orders_with_auth", "labels": [{"name": "feature", "value": "Получение заказов"}, {"name": "story", "value": "Получение заказов авторизованного пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetOrders"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "24144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}