{"name": "test_create_order_with_invalid_ingredient", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 500\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x107a8c470>\n\n    def test_create_order_with_invalid_ingredient(self):\n        order_data = {\n            \"ingredients\": [\"invalid_hash\"]\n        }\n        headers = {\"Authorization\": \"Bearer <accessToken>\"}\n        response = requests.post(f\"{BASE_URL}/orders\", json=order_data, headers=headers)\n>       assert response.status_code == 500  # Ошибка: невалидный хеш ингредиента\nE       assert 403 == 500\nE        +  where 403 = <Response [403]>.status_code\n\ntests/test_create_order.py:29: AssertionError"}, "start": 1732752224583, "stop": 1732752224858, "uuid": "c69fb2d4-626f-43a6-bb7d-989e576f26cc", "historyId": "9bf7d65d22acbc46bdc4ddb4293ba878", "testCaseId": "9bf7d65d22acbc46bdc4ddb4293ba878", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_with_invalid_ingredient", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "admins-MacBook-Pro.local"}, {"name": "thread", "value": "23420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}